### ISSUE TITLE
Dash in action names replaced by underscore

### ISSUE THREAD

**Issue by 19CMB94** [Maumagnaguagno/HyperTensioN#5]
Hello, 

I tried to verify the plans from HyperTensioN with the pandaPIparser ([https://github.com/panda-planner-dev/pandaPIparser](https://github.com/panda-planner-dev/pandaPIparser)) and noticed that I need to set the FAST_OUTPUT attribute to false in order to get the full plans. However, there seems so be an issue if the domain contains actions with a dash in their name. The dash appears to be replaced with an underscore. 

I tested it with the domain Barman-BDI, pfile01.hddl (from [https://github.com/panda-planner-dev/ipc2020-domains/blob/master/total-order/Barman-BDI/](https://github.com/panda-planner-dev/ipc2020-domains/blob/master/total-order/Barman-BDI/)) which contains the action fill-shot. In the plan I got it is called fill_shot (see plan attached) and therefore the plan is rejected by pandaPIparser (e.g. "Task with id=31 and task name "fill_shot" is not declared in the domain.")

I am using Ubuntu 20.04.2 LTS on the WSL 1 (Windows version: 10.0.19041.1083) in case this helps to track the error down. Unfortunately, I have no access to a native Ubuntu system running ruby.

Best regards

[plan.txt](https://github.com/Maumagnaguagno/HyperTensioN/files/6816622/plan.txt)

**Comment by Maumagnaguagno** [comment]
Yes, this is the expected behavior.
The original output is obtained with ``FAST_OUTPUT = true``, otherwise the more detailed plan output from IPC is used.
HyperTensioN always use lower-case characters and underscore instead of mixed case and dash/hyphen to avoid comparison and evaluation problems.
There is probably a flag to compare plans with this behavior, as I used this during the IPC.

**Comment by 19CMB94** [comment]
Thank you very much for your quick reply :)
