### ISSUE TITLE
:constants is not recognized in domain

### ISSUE THREAD

**Issue by Vir-Limerence** [Maumagnaguagno/HyperTensioN#8]
I have found that PDDL_Parser.rb cannot parse the ":constants" in the PDDL syntax, which is supported in most versions.

![image](https://github.com/Maumagnaguagno/HyperTensioN/assets/64056564/8da43561-9658-42fa-b214-214576fe8535)

**Comment by Maumagnaguagno** [comment]
Yes, this PDDL Parser does not support constants, this is by design.
This is not a problem in this project as this is not a classical planner.
The PDDL Parser implemented here is minimal to support my research in translation between classical and hierarchical planning models.
Even if support is added to the parser, the PDDL Compiler would output everything as objects, as they are internally the same, which could be confusing to users.
I also find constants a code smell, usually a constant can be combined with related predicates/actions.
